/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRtoPaymentsRouteImport } from './routes/_app/rto-payments'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPortalRouteImport } from './routes/_app/portal'
import { Route as AppInsurancePaymentsRouteImport } from './routes/_app/insurance-payments'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppAdvancesRouteImport } from './routes/_app/advances'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app/settings/company'
import { Route as AppSettingsBanksRouteImport } from './routes/_app/settings/banks'
import { Route as AppPortalProfileRouteImport } from './routes/_app/portal/profile'
import { Route as AppPortalNotificationsRouteImport } from './routes/_app/portal/notifications'
import { Route as AppPortalFilesRouteImport } from './routes/_app/portal/files'
import { Route as AppPaymentsOutRouteImport } from './routes/_app/payments/out'
import { Route as AppPaymentsInRouteImport } from './routes/_app/payments/in'
import { Route as AppMastersInsuranceTypesRouteImport } from './routes/_app/masters/insurance-types'
import { Route as AppMastersInsuranceCompaniesRouteImport } from './routes/_app/masters/insurance-companies'
import { Route as AppMastersFinanceBanksRouteImport } from './routes/_app/masters/finance-banks'
import { Route as AppMastersExpenseCategoriesRouteImport } from './routes/_app/masters/expense-categories'
import { Route as AppMastersDealersRouteImport } from './routes/_app/masters/dealers'
import { Route as AppMastersBrokersRouteImport } from './routes/_app/masters/brokers'
import { Route as AppFilesNewRouteImport } from './routes/_app/files/new'
import { Route as AppFilesIdRouteImport } from './routes/_app/files/$id'
import { Route as AppCustomersNewRouteImport } from './routes/_app/customers/new'
import { Route as AppCustomersIdRouteImport } from './routes/_app/customers/$id'
import { Route as AppCommissionsOutRouteImport } from './routes/_app/commissions/out'
import { Route as AppCommissionsInRouteImport } from './routes/_app/commissions/in'
import { Route as AppAgentFilesRouteImport } from './routes/_app/agent/files'
import { Route as AppAgentDashboardRouteImport } from './routes/_app/agent/dashboard'
import { Route as AppAgentCustomersRouteImport } from './routes/_app/agent/customers'
import { Route as AppAgentCommissionsRouteImport } from './routes/_app/agent/commissions'
import { Route as AppPortalFilesIdRouteImport } from './routes/_app/portal/files/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRtoPaymentsRoute = AppRtoPaymentsRouteImport.update({
  id: '/rto-payments',
  path: '/rto-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppInsurancePaymentsRoute = AppInsurancePaymentsRouteImport.update({
  id: '/insurance-payments',
  path: '/insurance-payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancesRoute = AppAdvancesRouteImport.update({
  id: '/advances',
  path: '/advances',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBanksRoute = AppSettingsBanksRouteImport.update({
  id: '/settings/banks',
  path: '/settings/banks',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalProfileRoute = AppPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalNotificationsRoute = AppPortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPortalFilesRoute = AppPortalFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppPortalRoute,
} as any)
const AppPaymentsOutRoute = AppPaymentsOutRouteImport.update({
  id: '/payments/out',
  path: '/payments/out',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsInRoute = AppPaymentsInRouteImport.update({
  id: '/payments/in',
  path: '/payments/in',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersInsuranceTypesRoute =
  AppMastersInsuranceTypesRouteImport.update({
    id: '/masters/insurance-types',
    path: '/masters/insurance-types',
    getParentRoute: () => AppRoute,
  } as any)
const AppMastersInsuranceCompaniesRoute =
  AppMastersInsuranceCompaniesRouteImport.update({
    id: '/masters/insurance-companies',
    path: '/masters/insurance-companies',
    getParentRoute: () => AppRoute,
  } as any)
const AppMastersFinanceBanksRoute = AppMastersFinanceBanksRouteImport.update({
  id: '/masters/finance-banks',
  path: '/masters/finance-banks',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersExpenseCategoriesRoute =
  AppMastersExpenseCategoriesRouteImport.update({
    id: '/masters/expense-categories',
    path: '/masters/expense-categories',
    getParentRoute: () => AppRoute,
  } as any)
const AppMastersDealersRoute = AppMastersDealersRouteImport.update({
  id: '/masters/dealers',
  path: '/masters/dealers',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersBrokersRoute = AppMastersBrokersRouteImport.update({
  id: '/masters/brokers',
  path: '/masters/brokers',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesNewRoute = AppFilesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppFilesRoute,
} as any)
const AppFilesIdRoute = AppFilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppFilesRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppCommissionsOutRoute = AppCommissionsOutRouteImport.update({
  id: '/commissions/out',
  path: '/commissions/out',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsInRoute = AppCommissionsInRouteImport.update({
  id: '/commissions/in',
  path: '/commissions/in',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentFilesRoute = AppAgentFilesRouteImport.update({
  id: '/agent/files',
  path: '/agent/files',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentDashboardRoute = AppAgentDashboardRouteImport.update({
  id: '/agent/dashboard',
  path: '/agent/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentCustomersRoute = AppAgentCustomersRouteImport.update({
  id: '/agent/customers',
  path: '/agent/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentCommissionsRoute = AppAgentCommissionsRouteImport.update({
  id: '/agent/commissions',
  path: '/agent/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalFilesIdRoute = AppPortalFilesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPortalFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/advances': typeof AppAdvancesRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/files': typeof AppFilesRouteWithChildren
  '/insurance-payments': typeof AppInsurancePaymentsRoute
  '/portal': typeof AppPortalRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/rto-payments': typeof AppRtoPaymentsRoute
  '/agent/commissions': typeof AppAgentCommissionsRoute
  '/agent/customers': typeof AppAgentCustomersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/files': typeof AppAgentFilesRoute
  '/commissions/in': typeof AppCommissionsInRoute
  '/commissions/out': typeof AppCommissionsOutRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/files/$id': typeof AppFilesIdRoute
  '/files/new': typeof AppFilesNewRoute
  '/masters/brokers': typeof AppMastersBrokersRoute
  '/masters/dealers': typeof AppMastersDealersRoute
  '/masters/expense-categories': typeof AppMastersExpenseCategoriesRoute
  '/masters/finance-banks': typeof AppMastersFinanceBanksRoute
  '/masters/insurance-companies': typeof AppMastersInsuranceCompaniesRoute
  '/masters/insurance-types': typeof AppMastersInsuranceTypesRoute
  '/payments/in': typeof AppPaymentsInRoute
  '/payments/out': typeof AppPaymentsOutRoute
  '/portal/files': typeof AppPortalFilesRouteWithChildren
  '/portal/notifications': typeof AppPortalNotificationsRoute
  '/portal/profile': typeof AppPortalProfileRoute
  '/settings/banks': typeof AppSettingsBanksRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/portal/files/$id': typeof AppPortalFilesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/advances': typeof AppAdvancesRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/files': typeof AppFilesRouteWithChildren
  '/insurance-payments': typeof AppInsurancePaymentsRoute
  '/portal': typeof AppPortalRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/rto-payments': typeof AppRtoPaymentsRoute
  '/agent/commissions': typeof AppAgentCommissionsRoute
  '/agent/customers': typeof AppAgentCustomersRoute
  '/agent/dashboard': typeof AppAgentDashboardRoute
  '/agent/files': typeof AppAgentFilesRoute
  '/commissions/in': typeof AppCommissionsInRoute
  '/commissions/out': typeof AppCommissionsOutRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/files/$id': typeof AppFilesIdRoute
  '/files/new': typeof AppFilesNewRoute
  '/masters/brokers': typeof AppMastersBrokersRoute
  '/masters/dealers': typeof AppMastersDealersRoute
  '/masters/expense-categories': typeof AppMastersExpenseCategoriesRoute
  '/masters/finance-banks': typeof AppMastersFinanceBanksRoute
  '/masters/insurance-companies': typeof AppMastersInsuranceCompaniesRoute
  '/masters/insurance-types': typeof AppMastersInsuranceTypesRoute
  '/payments/in': typeof AppPaymentsInRoute
  '/payments/out': typeof AppPaymentsOutRoute
  '/portal/files': typeof AppPortalFilesRouteWithChildren
  '/portal/notifications': typeof AppPortalNotificationsRoute
  '/portal/profile': typeof AppPortalProfileRoute
  '/settings/banks': typeof AppSettingsBanksRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/portal/files/$id': typeof AppPortalFilesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/advances': typeof AppAdvancesRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/files': typeof AppFilesRouteWithChildren
  '/_app/insurance-payments': typeof AppInsurancePaymentsRoute
  '/_app/portal': typeof AppPortalRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/rto-payments': typeof AppRtoPaymentsRoute
  '/_app/agent/commissions': typeof AppAgentCommissionsRoute
  '/_app/agent/customers': typeof AppAgentCustomersRoute
  '/_app/agent/dashboard': typeof AppAgentDashboardRoute
  '/_app/agent/files': typeof AppAgentFilesRoute
  '/_app/commissions/in': typeof AppCommissionsInRoute
  '/_app/commissions/out': typeof AppCommissionsOutRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/files/$id': typeof AppFilesIdRoute
  '/_app/files/new': typeof AppFilesNewRoute
  '/_app/masters/brokers': typeof AppMastersBrokersRoute
  '/_app/masters/dealers': typeof AppMastersDealersRoute
  '/_app/masters/expense-categories': typeof AppMastersExpenseCategoriesRoute
  '/_app/masters/finance-banks': typeof AppMastersFinanceBanksRoute
  '/_app/masters/insurance-companies': typeof AppMastersInsuranceCompaniesRoute
  '/_app/masters/insurance-types': typeof AppMastersInsuranceTypesRoute
  '/_app/payments/in': typeof AppPaymentsInRoute
  '/_app/payments/out': typeof AppPaymentsOutRoute
  '/_app/portal/files': typeof AppPortalFilesRouteWithChildren
  '/_app/portal/notifications': typeof AppPortalNotificationsRoute
  '/_app/portal/profile': typeof AppPortalProfileRoute
  '/_app/settings/banks': typeof AppSettingsBanksRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/portal/files/$id': typeof AppPortalFilesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/advances'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/files'
    | '/insurance-payments'
    | '/portal'
    | '/reports'
    | '/rto-payments'
    | '/agent/commissions'
    | '/agent/customers'
    | '/agent/dashboard'
    | '/agent/files'
    | '/commissions/in'
    | '/commissions/out'
    | '/customers/$id'
    | '/customers/new'
    | '/files/$id'
    | '/files/new'
    | '/masters/brokers'
    | '/masters/dealers'
    | '/masters/expense-categories'
    | '/masters/finance-banks'
    | '/masters/insurance-companies'
    | '/masters/insurance-types'
    | '/payments/in'
    | '/payments/out'
    | '/portal/files'
    | '/portal/notifications'
    | '/portal/profile'
    | '/settings/banks'
    | '/settings/company'
    | '/settings/users'
    | '/portal/files/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/advances'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/files'
    | '/insurance-payments'
    | '/portal'
    | '/reports'
    | '/rto-payments'
    | '/agent/commissions'
    | '/agent/customers'
    | '/agent/dashboard'
    | '/agent/files'
    | '/commissions/in'
    | '/commissions/out'
    | '/customers/$id'
    | '/customers/new'
    | '/files/$id'
    | '/files/new'
    | '/masters/brokers'
    | '/masters/dealers'
    | '/masters/expense-categories'
    | '/masters/finance-banks'
    | '/masters/insurance-companies'
    | '/masters/insurance-types'
    | '/payments/in'
    | '/payments/out'
    | '/portal/files'
    | '/portal/notifications'
    | '/portal/profile'
    | '/settings/banks'
    | '/settings/company'
    | '/settings/users'
    | '/portal/files/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/advances'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/files'
    | '/_app/insurance-payments'
    | '/_app/portal'
    | '/_app/reports'
    | '/_app/rto-payments'
    | '/_app/agent/commissions'
    | '/_app/agent/customers'
    | '/_app/agent/dashboard'
    | '/_app/agent/files'
    | '/_app/commissions/in'
    | '/_app/commissions/out'
    | '/_app/customers/$id'
    | '/_app/customers/new'
    | '/_app/files/$id'
    | '/_app/files/new'
    | '/_app/masters/brokers'
    | '/_app/masters/dealers'
    | '/_app/masters/expense-categories'
    | '/_app/masters/finance-banks'
    | '/_app/masters/insurance-companies'
    | '/_app/masters/insurance-types'
    | '/_app/payments/in'
    | '/_app/payments/out'
    | '/_app/portal/files'
    | '/_app/portal/notifications'
    | '/_app/portal/profile'
    | '/_app/settings/banks'
    | '/_app/settings/company'
    | '/_app/settings/users'
    | '/_app/portal/files/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rto-payments': {
      id: '/_app/rto-payments'
      path: '/rto-payments'
      fullPath: '/rto-payments'
      preLoaderRoute: typeof AppRtoPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insurance-payments': {
      id: '/_app/insurance-payments'
      path: '/insurance-payments'
      fullPath: '/insurance-payments'
      preLoaderRoute: typeof AppInsurancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advances': {
      id: '/_app/advances'
      path: '/advances'
      fullPath: '/advances'
      preLoaderRoute: typeof AppAdvancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/banks': {
      id: '/_app/settings/banks'
      path: '/settings/banks'
      fullPath: '/settings/banks'
      preLoaderRoute: typeof AppSettingsBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/profile': {
      id: '/_app/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AppPortalProfileRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/notifications': {
      id: '/_app/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof AppPortalNotificationsRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/portal/files': {
      id: '/_app/portal/files'
      path: '/files'
      fullPath: '/portal/files'
      preLoaderRoute: typeof AppPortalFilesRouteImport
      parentRoute: typeof AppPortalRoute
    }
    '/_app/payments/out': {
      id: '/_app/payments/out'
      path: '/payments/out'
      fullPath: '/payments/out'
      preLoaderRoute: typeof AppPaymentsOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/in': {
      id: '/_app/payments/in'
      path: '/payments/in'
      fullPath: '/payments/in'
      preLoaderRoute: typeof AppPaymentsInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/insurance-types': {
      id: '/_app/masters/insurance-types'
      path: '/masters/insurance-types'
      fullPath: '/masters/insurance-types'
      preLoaderRoute: typeof AppMastersInsuranceTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/insurance-companies': {
      id: '/_app/masters/insurance-companies'
      path: '/masters/insurance-companies'
      fullPath: '/masters/insurance-companies'
      preLoaderRoute: typeof AppMastersInsuranceCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/finance-banks': {
      id: '/_app/masters/finance-banks'
      path: '/masters/finance-banks'
      fullPath: '/masters/finance-banks'
      preLoaderRoute: typeof AppMastersFinanceBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/expense-categories': {
      id: '/_app/masters/expense-categories'
      path: '/masters/expense-categories'
      fullPath: '/masters/expense-categories'
      preLoaderRoute: typeof AppMastersExpenseCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/dealers': {
      id: '/_app/masters/dealers'
      path: '/masters/dealers'
      fullPath: '/masters/dealers'
      preLoaderRoute: typeof AppMastersDealersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters/brokers': {
      id: '/_app/masters/brokers'
      path: '/masters/brokers'
      fullPath: '/masters/brokers'
      preLoaderRoute: typeof AppMastersBrokersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files/new': {
      id: '/_app/files/new'
      path: '/new'
      fullPath: '/files/new'
      preLoaderRoute: typeof AppFilesNewRouteImport
      parentRoute: typeof AppFilesRoute
    }
    '/_app/files/$id': {
      id: '/_app/files/$id'
      path: '/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof AppFilesIdRouteImport
      parentRoute: typeof AppFilesRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/commissions/out': {
      id: '/_app/commissions/out'
      path: '/commissions/out'
      fullPath: '/commissions/out'
      preLoaderRoute: typeof AppCommissionsOutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions/in': {
      id: '/_app/commissions/in'
      path: '/commissions/in'
      fullPath: '/commissions/in'
      preLoaderRoute: typeof AppCommissionsInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/files': {
      id: '/_app/agent/files'
      path: '/agent/files'
      fullPath: '/agent/files'
      preLoaderRoute: typeof AppAgentFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/dashboard': {
      id: '/_app/agent/dashboard'
      path: '/agent/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AppAgentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/customers': {
      id: '/_app/agent/customers'
      path: '/agent/customers'
      fullPath: '/agent/customers'
      preLoaderRoute: typeof AppAgentCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent/commissions': {
      id: '/_app/agent/commissions'
      path: '/agent/commissions'
      fullPath: '/agent/commissions'
      preLoaderRoute: typeof AppAgentCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal/files/$id': {
      id: '/_app/portal/files/$id'
      path: '/$id'
      fullPath: '/portal/files/$id'
      preLoaderRoute: typeof AppPortalFilesIdRouteImport
      parentRoute: typeof AppPortalFilesRoute
    }
  }
}

interface AppCustomersRouteChildren {
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppFilesRouteChildren {
  AppFilesIdRoute: typeof AppFilesIdRoute
  AppFilesNewRoute: typeof AppFilesNewRoute
}

const AppFilesRouteChildren: AppFilesRouteChildren = {
  AppFilesIdRoute: AppFilesIdRoute,
  AppFilesNewRoute: AppFilesNewRoute,
}

const AppFilesRouteWithChildren = AppFilesRoute._addFileChildren(
  AppFilesRouteChildren,
)

interface AppPortalFilesRouteChildren {
  AppPortalFilesIdRoute: typeof AppPortalFilesIdRoute
}

const AppPortalFilesRouteChildren: AppPortalFilesRouteChildren = {
  AppPortalFilesIdRoute: AppPortalFilesIdRoute,
}

const AppPortalFilesRouteWithChildren = AppPortalFilesRoute._addFileChildren(
  AppPortalFilesRouteChildren,
)

interface AppPortalRouteChildren {
  AppPortalFilesRoute: typeof AppPortalFilesRouteWithChildren
  AppPortalNotificationsRoute: typeof AppPortalNotificationsRoute
  AppPortalProfileRoute: typeof AppPortalProfileRoute
}

const AppPortalRouteChildren: AppPortalRouteChildren = {
  AppPortalFilesRoute: AppPortalFilesRouteWithChildren,
  AppPortalNotificationsRoute: AppPortalNotificationsRoute,
  AppPortalProfileRoute: AppPortalProfileRoute,
}

const AppPortalRouteWithChildren = AppPortalRoute._addFileChildren(
  AppPortalRouteChildren,
)

interface AppRouteChildren {
  AppAdvancesRoute: typeof AppAdvancesRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFilesRoute: typeof AppFilesRouteWithChildren
  AppInsurancePaymentsRoute: typeof AppInsurancePaymentsRoute
  AppPortalRoute: typeof AppPortalRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppRtoPaymentsRoute: typeof AppRtoPaymentsRoute
  AppAgentCommissionsRoute: typeof AppAgentCommissionsRoute
  AppAgentCustomersRoute: typeof AppAgentCustomersRoute
  AppAgentDashboardRoute: typeof AppAgentDashboardRoute
  AppAgentFilesRoute: typeof AppAgentFilesRoute
  AppCommissionsInRoute: typeof AppCommissionsInRoute
  AppCommissionsOutRoute: typeof AppCommissionsOutRoute
  AppMastersBrokersRoute: typeof AppMastersBrokersRoute
  AppMastersDealersRoute: typeof AppMastersDealersRoute
  AppMastersExpenseCategoriesRoute: typeof AppMastersExpenseCategoriesRoute
  AppMastersFinanceBanksRoute: typeof AppMastersFinanceBanksRoute
  AppMastersInsuranceCompaniesRoute: typeof AppMastersInsuranceCompaniesRoute
  AppMastersInsuranceTypesRoute: typeof AppMastersInsuranceTypesRoute
  AppPaymentsInRoute: typeof AppPaymentsInRoute
  AppPaymentsOutRoute: typeof AppPaymentsOutRoute
  AppSettingsBanksRoute: typeof AppSettingsBanksRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancesRoute: AppAdvancesRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFilesRoute: AppFilesRouteWithChildren,
  AppInsurancePaymentsRoute: AppInsurancePaymentsRoute,
  AppPortalRoute: AppPortalRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppRtoPaymentsRoute: AppRtoPaymentsRoute,
  AppAgentCommissionsRoute: AppAgentCommissionsRoute,
  AppAgentCustomersRoute: AppAgentCustomersRoute,
  AppAgentDashboardRoute: AppAgentDashboardRoute,
  AppAgentFilesRoute: AppAgentFilesRoute,
  AppCommissionsInRoute: AppCommissionsInRoute,
  AppCommissionsOutRoute: AppCommissionsOutRoute,
  AppMastersBrokersRoute: AppMastersBrokersRoute,
  AppMastersDealersRoute: AppMastersDealersRoute,
  AppMastersExpenseCategoriesRoute: AppMastersExpenseCategoriesRoute,
  AppMastersFinanceBanksRoute: AppMastersFinanceBanksRoute,
  AppMastersInsuranceCompaniesRoute: AppMastersInsuranceCompaniesRoute,
  AppMastersInsuranceTypesRoute: AppMastersInsuranceTypesRoute,
  AppPaymentsInRoute: AppPaymentsInRoute,
  AppPaymentsOutRoute: AppPaymentsOutRoute,
  AppSettingsBanksRoute: AppSettingsBanksRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
